"""
Version 9's response to the review of version 8 (21 findings, 5 October 2026): each finding checked against the firms' own
pages (rules_snapshot_v9.json) and against the code, with what was wrong and what version 9 does. [[KEY]] fields are filled
from the version 9 results when the document is built. NEW lists further errors found while fixing them. PRIOR summarises
the responses of versions 7 and 8 to the earlier reviews (full texts: docs/v7_review_response.md, docs/v8_review_response.md).
"""

R = [
 dict(n=1, title="The finite-budget simulation spent cash that had not arrived", verdict="agreed",
      wrong="The portfolio engine processed trades in the order of their entry, but resolved each trade to its exit at once and let the account's generator run on: a purchase made while processing one account's later events could release a payout receipt dated after another account's earlier purchase, which then used that cash. The wallet's own minimum was positive while the cash dated by the ledger was not: five of the 1,400 budget lives went below zero, the worst ($10,000 budget, life 100,016) $6,971 below zero at hour 2,047, as the review reproduced.",
      fix="Every purchase is now an event at its own time on the simulation's queue, processed in time order with the trades' entries; it is paid from the cash dated at or before it (starting cash, earlier purchases, payouts received by then) and otherwise waits a day at a time. The wallet asserts that it is used in time order, and every budget life asserts that the cash dated by its ledger never falls below zero. tests_v9.py reruns the review's witness life (100,016) and two others at $10,000 and $30,000. [[BUDGET_FIX]] Monthly subscriptions and activation fees are not in the budget runs (the recommended plan has none; the code refuses them with a budget)."),
 dict(n=2, title="The path generator's error bound was false", verdict="agreed",
      wrong="Section 3.3 bounded the chance that independently drawn sub-step extremes misrepresent a bracket by exp(-W^2/v), arguing that the exponent is smallest with both end points at the middle. That holds only for a sub-step with no net move; with end points near opposite barriers the exponent is close to zero. The review's counterexample (l = 0, u = 1, a = 0.01, b = 0.99, v = 0.01) has independent-draw probability exp(-3.96) = 0.019 and exact probability exp(-4) = 0.0183, against the claimed bound of 3.7e-44. The 'about 2e-48 per trade' check and the claim of exactness within the bound were therefore unsupported.",
      fix="A valid bound replaces it (pathfirm.bridge_err, Section 3.3). Given a sub-step's end points, the generator's outcome (no touch, stop, target) differs from the exact law in total variation by at most the chance that both barriers are touched under either law; the exact chance is at most twice the independent one (strong Markov property at the first touch), so the error is at most 3 P_ind. For a net move delta the largest P_ind over the starting point is exp(-(W^2 - delta^2)/v); the move is independent of where the sub-step starts and of whether the trade is still open, so each watched sub-step contributes at most G(r) = E[min(1, 3 exp(-(r^2 - Z^2)))], r = W/sqrt(v), which has a closed form and is close to exp(-r^2/2), the square root of the old figure. The engine adds G over every sub-step in which a trade watches both barriers. [[BRIDGE_RESULT]] tests_v9.py reproduces the counterexample with the exact two-barrier series and checks the strong-Markov bound on 4,000 random bridges. The fair-chance fallback for a sub-step touching both barriers stays; its effect lies inside this bound."),
 dict(n=3, title="Terminal trades did not enforce the account floor during the trade", verdict="agreed",
      wrong="The floor entered a trade's size but not its path: a futures account with $100 above its floor traded one contract with a $170 stop, so a path that first went $110 against it and then $255 for it ended in a $255 win where the firm would have closed the account at $100. On CFDs a risk below $1 per $100K was rounded up to $1 and a loss clipped back to the floor afterwards, which changed the payoff (mean +$0.44 instead of -$0.03 in the review's example) without changing the chance of reaching the floor. tests_v8.py checked only end balances.",
      fix="The account's breach level (the nearer of the floor and today's loss limit, cost included) is a barrier of every trade (pathfirm.resolve): reaching it ends the account at that moment, whatever the price does later. The terminal trade places its stop at that level itself, at the volume the smallest position allows, so the stop is a real order at the floor; a loss is no longer clipped anywhere. tests_v9.py reruns the review's futures witness (now a breach at -$100, against +$255 before) and 40,000 minimal-lot trades with $0.50 left, whose mean is zero within its interval and whose lowest result is exactly -$0.50. [[FLOOR_RESULT]]"),
 dict(n=4, title="The CFD engine had no lots", verdict="agreed",
      wrong="Only futures were whole contracts. A CFD position was the exact notional l/s, however small, and the $1 per $100K floor on the risk was not a lot size: the smallest real position's risk depends on the contract, the price and the stop distance.",
      fix="Every market now trades whole volume steps at its contract size (pathfirm.LOTS): index CFDs one index unit a lot ($1 a point, FTMO's MT5 contract size for its index CFDs), gold 100 ounces, currency pairs 100,000 units, volumes from 0.01 lot in steps of 0.01; the micro Nasdaq future one contract at $2 a point. The volume is rounded down, never below the smallest position; the risk, the take-profit, the cost and the margin are computed from the rounded volume. A take-profit set by a cap keeps its amount (the price is set for exactly that win), so a target-landing trade still lands; otherwise the win scales with the rounded risk. The smallest position's risk enters the sizing rule wherever the plan's own risk would be smaller. [[LOT_RESULT]] Other brokers' contract sizes change only the rounding."),
 dict(n=5, title="Filler days were calendar entries, not trades", verdict="agreed",
      wrong="filler_days marked a missing day as traded and moved the clock on; no position, price, cost or result existed. Version 8 called these 'minimal filler trades' and relied on a $20 buffer to keep the target.",
      fix="A filler is now a real position (pathfirm.resolve, kind 'filler'): 0.01 lot (one futures contract), opened at the day's first permitted hour, closed at the market after 3 minutes, with its cost, its result in the balance and the breach barrier of finding 3; the day counts only if the firm's day definition is met (BrightFunded: held 60 seconds). If a filler's loss takes the balance under the firm's target, ordinary trading resumes. The $20 per $100K margin stays as a plan choice. [[FILLER_RESULT]]"),
 dict(n=6, title="'Fewer than 1 in 1,000 within two minutes' was false", verdict="agreed",
      wrong="For a driftless Brownian motion a one-sided level 0.6 hourly sd away is touched within 2 minutes with probability erfc(0.6 sqrt(15)) = 0.1015%, above 0.1%, and a bracket with both levels at 0.6 sd is closed within 2 minutes with probability about 0.203%. The distance floor was presented as a universal guarantee; an observed low share of short trades is a different statement.",
      fix="The claim is withdrawn everywhere. The 0.6 sd minimum distance stays as a plan choice (it keeps costs a fair description), with the exact two-barrier probabilities of a close within 2 minutes stated for each chosen setting and the measured share of trades that may have lasted under 2 minutes reported separately. Where a firm has a duration rule it is now met by construction or checked on the account's own trades (finding 7). [[SHORT_RESULT]]"),
 dict(n=7, title="Duration rules were not enforced where they apply", verdict="agreed",
      wrong="Blue Guardian states a 2-minute minimum holding time; Alpha Capital assesses each account's average duration, the majority of its trades and the share of its gross profit from trades over 2 minutes, with a restart (evaluation) or the removal of profits (qualified account) on failure; BrightFunded counts a trading day only if a position on it was open 60 seconds. Version 8 had no per-firm handling: a global short-trade count, a distance argument (finding 6), and BrightFunded days counted after every trade.",
      fix="Blue Guardian: the plan places the bracket only after 3 minutes (hold_min); until then only the breach level can close the position, and at 3 minutes it is closed at the market if the price is already beyond the stop or the target; a trade that could still close sooner (only a breach can) is treated as ending the account. Alpha Capital: the rule is checked on the account's own trades at every phase pass and payout request, with the firm's consequences applied (dur_rule; durations are lower bounds). BrightFunded: a day counts only if a trade on it was held at least one minute. [[DUR_RESULT]] The engine reports 'no violation by construction' (Blue Guardian), 'checked, consequence applied' (Alpha) and 'counted by the firm's definition' (BrightFunded) separately."),
 dict(n=8, title="Fintokei's filler permission was not established", verdict="agreed",
      wrong="Fintokei's all-in article objects to 'much smaller trades ... just to meet the minimum 3-day trading requirement', and its trading-day definition requires an executed trade with a real market outcome. Version 8's rule table called token trades prohibited while its engine description said 'fillers allowed', and its response inferred permission from the day definition.",
      fix="No filler trades at Fintokei (no_fillers). The plan's 40% concentration policy already needs three winning days per phase, so a phase never needs one; a funded cycle short of its 3 trading days collects them with ordinary trades of the plan, one a day. Alpha Capital, which forbids minimal lots on qualified accounts, is treated the same way in its evaluations too. The other firms' fillers rest on their day definitions (a day on which a position is opened; no minimum volume stated), an assumption the no-filler sensitivity measures. [[FINTOKEI_FILL]]"),
 dict(n=9, title="Hola Prime's 14-day window was absent", verdict="agreed",
      wrong="The bi-weekly payout needs three profitable days (+0.5% of the initial balance) within a 14-day period; the engine counted them since the last payout, and a cycle can last longer than 14 days. The review's controlled run (profitable days 0, 22 and 23) was paid on day 23.8.",
      fix="The engine keeps the dates of the cycle's profitable days and counts those within the 14 calendar days ending on the request day (profit_days_window); the daily profit target of 6.4 is recomputed as old days leave the window. tests_v9.py reruns the review's witness: no payout; with the days moved to 15, 22 and 23, a payout. [[HOLA_RESULT]]"),
 dict(n=10, title="Fintokei's recurring payout clock ran from the request", verdict="agreed",
      wrong="Fintokei allows a withdrawal 14 days after the last successfully processed payout; version 8 set the next date 14 days after the request and dated the cash one day later, so a request could come 13 days after the previous payout's processing.",
      fix="Request, processing and receipt are separate times: the cash arrives after the firm's processing time in working days, and at Fintokei the next request is allowed 14 days after that (cycle_from_processed). The plan assumes the standard (not instant) method, one working day. tests_v9.py checks every later Fintokei request: [[FINTOKEI_CLOCK]]"),
 dict(n=11, title="The portfolio kept a closed position open until its next entry", verdict="agreed",
      wrong="The resolver returned the hours until another entry may be considered (rounded to the hour, plus an hour after a late exit), and the portfolio stored that as the position's exit: a bracket closed at minute 55 counted as open for another hour, and another account could copy its direction. Maven's rolling 30-day window dated closed profit by the same next-entry time.",
      fix="The resolver returns the exit time (the end of the exit minute) separately from the next permitted entry. Exposure (the shared-direction rule), Maven's dated closed profit and every day attribution use the exit; only the next entry uses the 10-minute rule. tests_v9.py checks every trade of a life with 10,886 trades: each copied direction comes from a position still open at the entry and no uncopied entry had one open. All portfolio runs were repeated."),
 dict(n=12, title="Part II's 'stationary long-run rate' was not what the estimator measured", verdict="agreed",
      wrong="optimize_v8.run starts every attempt with a new trader at a random point of a path and at a random hour, with no state carried over and with a random direction, while the text described a Markov renewal estimate under the stationary start-state distribution with credits and windows carried. Random starts are not that distribution, and the continuing strategy uses the 5-hour direction rule; the futures state also includes the price level.",
      fix="The search still ranks settings by the random-start attempt ratio, now named so. Version 9 adds a continuing-slot stage (continuing_v9.py): for every final setting, a slot runs attempts back to back for nine years on one path and calendar with everything it carries (path position and price level, calendar, The5ers credits, monthly and activation fees, dated payouts, the 5-hour direction rule), the first year discarded as warm-up, 12 slots on each of 16 new paths. Its rate, with a path-cluster interval, is Part II's long-run rate, and the portfolio's choices between alternatives use it. [[CONT_RESULT]]"),
 dict(n=13, title="A fresh account does not make the two phases independent", verdict="agreed",
      wrong="Section 6.1 said the second phase's trades are independent of the first's, so P(pass 2 | passed 1) equals an unconditional P2. The starting weekday, hour and (futures) price level of phase 2 depend on how phase 1 ended.",
      fix="6.1 keeps the always-valid product P(both) = P1 x P(2 | 1), defines the engine's P2 as that conditional probability (the engine simulates both phases in sequence on one path, so it estimates it directly), and reserves the product of unconditional probabilities for the calendar-free chain, where it is exact."),
 dict(n=14, title="Pass-rate intervals were binomial, not path-clustered", verdict="agreed",
      wrong="The '&plusmn;' on every two-phase pass rate was 1.96 sqrt(P(1-P)/n) over 24,000 attempts that reuse 16 paths, while the text promised the larger of a cluster interval and an attempt-level one.",
      fix="optimize_v9 keeps each path's attempts and passes and prints the larger of the cluster-robust interval (Student t, 15 degrees of freedom) and the attempt-level one, as for the EV per month. [[P_CI_RESULT]]"),
 dict(n=15, title="The interval of the summed programme rates left out the shared paths", verdict="agreed",
      wrong="Every final figure used the same 16 paths, so programmes on one market (and sizes of one programme) are correlated, but the sum's interval added the programmes' widths in quadrature. Its 'about 1.1 standard errors' comparison was therefore not established. tq(23) also took the table's 25-degree value (2.060 for 2.069). The claim that overlapping intervals made a choice indistinguishable from noise ignored that candidates share paths and seeds, so a paired difference can be precise when the separate intervals overlap. The fresh final figures were also reused to choose markets and allocations, so the Part II sum of the chosen programmes is not free of selection.",
      fix="Every final and continuing row keeps its per-path sums; the interval of a sum of programmes is computed from the per-path sums of the whole portfolio (its full covariance), with exact Student quantiles (optimize_v9.tq). Comparisons between settings use paired per-path differences. The text states that the portfolio's choices use the continuing-slot figures and that the Part II sum is therefore not a selection-free estimate; the portfolio simulations run on fresh paths, so their means are. [[SUM_CI_RESULT]]"),
 dict(n=16, title="Cycle cash formulas and cash tables used the nominal payout target", verdict="agreed",
      wrong="Since version 8 a win may pass the target, so a successful cycle pays its balance at success, not X. 7.2's formula, the formula sheet and the cash-per-payout tables multiplied by X1 and X while the chain's withdrawal used the balance at success: for FTMO the mean paid per successful cycle was $20,082, not $20,000, and the mean cash with exactly one paid cycle $16,673.51, not $16,608. Maven's mean, $4,701.92, was below the nominal $4,900 because of finding 17.",
      fix="7.2 and the formula sheet use m1 = E[balance at success, cycle 1] and m = E[balance at success, later cycles]: E[C] = alpha (m1 q1 + m q1 q/(1-q)) + R q1 q^(r-1), and GFT's two special cycles likewise. The tables give E[cash | n cycles paid] = alpha (m1 + (n-1) m) + refund, from the chain, labelled as the chain's reset-cycle model. [[CASH_RESULT]]"),
 dict(n=17, title="Maven's chain and engine stopped on different balances", verdict="agreed",
      wrong="The chain declared a cycle successful whenever the distance to the ceiling was below the smallest allowed win (about $865 at the chosen setting), so it paid $4,500 at a balance where the engine, which pays at the target or within $1 of the ceiling, kept trading with a smaller position. Agreement of expected cash within an interval did not show that the two models used one rule.",
      fix="The chain now uses the engine's rule: the ceiling is a cap on every win, a win too small for the minimum distance is placed with its risk lowered (as the engine does), and a cycle is paid only at the target or within $1 of the ceiling. Verification 7 compares the paid amount per successful cycle and the first cycle's success rate between the engine and the chain on the same stopping set. [[MAVEN_RESULT]]"),
 dict(n=18, title="'Fewest trades means least cost' does not follow under variable stakes", verdict="agreed",
      wrong="With cost proportional to risk, the expected total cost is rho E[sum of risks], not a constant times the number of trades, and with overshoots the pass probability depends on the mean balance at success too. Invoking bold play did not fill those steps.",
      fix="5.6 now states the cost as rho E[sum of l_i] and the pass probability through both K and the mean balance at success, and presents the search's winners as empirical results for the grid searched; the bold-play theorem is cited only for its own model."),
 dict(n=19, title="A daily profit stop is not automatically neutral for the pass probability", verdict="agreed",
      wrong="6.4 said that stopping at a daily target is a stopping time, so in a cost-free fair game the pass probability is unchanged. Optional stopping preserves the expected stopped balance, not a hitting probability; with overshoots P = B/(B + E[X_end | pass]), which a policy change can move (a fair game ending at +1 or -1 passes with probability 1/2, one ending at +2 or -1 with 1/3).",
      fix="6.4 states the invariance only for exact landing at fixed boundaries, and otherwise refers to the engine, which measures the effect."),
 dict(n=20, title="Working-day reviews were calendar days", verdict="agreed",
      wrong="The engine added review x 24 hours, so a three-working-day review after a Friday ended on Monday.",
      fix="Reviews and payout processing are working days on the path's calendar (acct_mc._bdays): three working days after a Friday afternoon end on Wednesday afternoon. tests_v9.py checks it."),
 dict(n=21, title="Smaller document errors", verdict="agreed",
      wrong="p.75: two 200K accounts were said to pay 'exactly twice' four 100K accounts' cash, which is equal. p.13: the boxed terminal rule ran off the page. p.38: the The5ers size table called every row the plan's setting scaled, while the 100K row is High Stakes Classic and the small rows New with their own settings. p.84: the cost stresses (200 paired lives, baseline $61,227) were compared with the 1,200-life headline. p.19 and response 11: counting from the first trade was said to delay the clock 'at most hours', but a funded account issued after Friday's cut-off waits until Monday.",
      fix="Each is corrected: 'equal to' (and, with whole lots and minimal fillers, equal only up to rounding, which the scaling test now reports as a paired difference); the formula is reflowed; the size table names each row's programme and setting; the stresses are compared with their own paired baseline; the first-trade clock can wait days."),
]

NEW = [
 dict(n="n17", title="A position opened at the open of an hour that had already begun",
      what="Found by the payout-clock test of tests_v9.py. The engine's clock can stand part-way into an hour (a random start, a day boundary plus a few seconds); the trader then opened the position at the open of that hour, up to an hour before the decision, and the first funded trade's time, which starts the payout clock, was taken from the clock rather than from the bar. There is no look-ahead in the decision (the direction uses completed hours only, and the price is a martingale), but the dates were inconsistent. A position now opens at the first hourly open not before the clock, and every date is that bar's open."),
 dict(n="n18", title="A rounded futures position fell short of the target it was sized to reach",
      what="Version 8 rounded a futures position down to whole contracts and scaled both the risk and the win by the same factor, so a trade sized to close the gap to a target fell short by up to the dropped fraction and needed a further trade. A take-profit set by a cap now keeps its amount at the rounded volume (the price is placed for that win), on futures and CFDs alike."),
 dict(n="n19", title="Maven's minimum reward:risk on the last trade near the floor",
      what="The plan never trades Maven below 1 : 1.5. On a terminal trade the risk is the room to the floor, not the planned risk, and lowering the planned risk (the rule's remedy on a normal trade) changed only the volume. The terminal trade's target is now raised to 1.5 times the room where the caps allow, in the engine and the chain alike."),
]

PRIOR = ("Version 8 answered a 27-point review of version 7 (26 agreed in full, one in part) and found 16 further errors: daily-loss bases "
         "per firm, FXIFY Classic without a refund, Fintokei's and Alpha's payout gates, Maven's ceiling and rolling cap, one-minute "
         "sub-steps, a terminal rule that ends every failed account in a breach, the 10-minute gap from the exit minute, futures valued "
         "at the path's level, keyed random streams, trades decided on the day they open, and payouts recorded when paid. Version 7 "
         "answered a 35-point review of version 6 (no bold play, the daily flat, cost-aware sizing, margin at every entry, the exact "
         "chain and cluster intervals). The full responses are docs/v8_review_response.md and docs/v7_review_response.md.")
