"""
The version 6 review (35 points, 4 October 2026) and what version 7 does about each, plus the further errors found while
fixing them. Rendered as Appendix A of the version 7 document; numbers in [[...]] are filled from the version 7 runs.
verdict: "agreed" (the point is right and is fixed), "agreed, extended" (fixed, and the fix found more), "agreed in part".
"""
R = [
 # ---------------------------------------------------------------- A. mathematical model
 dict(n=1, title="The written near-floor policy strands accounts", verdict="agreed",
      wrong="The document's rule (risk = min(L, room - $100), wait for tomorrow when risk < $150) can leave an account a few "
            "dollars above its static floor with no trade allowed, for ever. The version 6 engine did not follow the written "
            "rule either: when the room fell below $1 it traded a micro position of the whole remaining room.",
      fix="One terminal rule, the same in the text, the engine (acct_mc.py run_stage / run_funded) and the chain "
          "(analytic_v7.chain): risk l(x) = min(L, (x + B - buffer)/(1 + rho)); when that room is below l_min = max(0.1 L, one "
          "futures contract) the attempt or funded account ends there and is recorded as a failure. The plan stops trading the "
          "account and buys the replacement; nothing in any firm's rules requires trading an account to its floor."),
 dict(n=2, title="The pass-probability identity assumes exact terminal values", verdict="agreed",
      wrong="P = (B - E[cost])/(A + B) was presented as exact for the plan; it needs every failure to end exactly at -B.",
      fix="The chain now computes E[X_end | failure] and checks the general accounting equation "
          "P A + (1 - P) E[X_end | fail] = -E[total cost] numerically ([[GAP_MAX]] largest gap over every chosen programme). "
          "Under the version 7 rule every failure ends between -B + buffer and -B + buffer + l_min(1 + rho), so the textbook "
          "form differs from the exact P by [[TEXTBOOK_DIFF]]."),
 dict(n=3, title="The opening zero-cost example over-counts the refund", verdict="agreed",
      wrong="-632 + (1/3)(8,000 + 632) = $2,245 counts the refund on every pass; it comes only with a first payout.",
      fix="With the first payout reached with chance q = D/(D + X): E[V] = -F + P(alpha D + q R) = $2,087.33 at X = $30,000 "
          "(the version 6 setting) and $2,140.00 at X = $10,000; $2,245 is the limit X -> 0. Chapter 1 now uses this form."),
 dict(n=4, title="Bold-play tables violate the reward:risk cap", verdict="agreed",
      wrong="Several tables used w = A - x when k l(x) < A - x, so the displayed probabilities belonged to trades the plan "
            "never places; 'k ~ 27 reaches every target' ignored the shrinking risk near the floor; changing k does not "
            "change the order size.",
      fix="Every table is generated by analytic_v7.bold_path from the same state-wise transition as the solver, "
          "w(x) = min(k l(x), A - x, cap); rows where a win does not end the phase are marked and no product formula is "
          "printed for them; the chain value is the one quoted. Under the 40% concentration policy no single win can end a "
          "phase, so the one-trade 'bold' tables are gone."),
 dict(n=5, title="Entry-time stops do not protect equity-based daily resets", verdict="agreed",
      wrong="With daily limits measured on midnight equity (Fintokei) or the higher of balance and equity (FundingPips, GFT, "
            "The5ers, FXIFY, Blue Guardian, Maven), an open profit at the reset raises the day's floor; a smooth reversal "
            "can breach it with no gap.",
      fix="Plan policy: no entry from 19:00 UTC, every position closed at the 20:00 UTC open, so the account is flat at every "
          "firm's reset (all between 20:00 and 00:00 UTC). Balance then equals equity at the reset and the engine's limit "
          "is the firm's. Fintokei's limit is also modelled as 5% of start-of-day equity (dll_rel)."),
 dict(n=6, title="The risk cap left out costs", verdict="agreed",
      wrong="A stopped trade loses l + c; subtracting $100/$200 reserves does not guarantee l + c fits the room.",
      fix="l = min(L, room/(1 + rho)) for both the floor and the daily limit (rho = round-trip cost per dollar of risk, "
          "scaled with every cost stress). With the daily flat there is no financing to add."),
 dict(n=7, title="Bracket formulas do not include random financing", verdict="agreed",
      wrong="p = l/(l + w + c), mean -c and variance l(w + c) hold for a fixed known cost and binary outcomes only.",
      fix="The formulas are stated for that model only. Under the daily flat no position is held through a rollover, so "
          "financing is zero; the flat-time close makes some outcomes intermediate, which the engine simulates and the "
          "chain does not (the difference is reported)."),
 dict(n=8, title="The withdrawal identity was overstated", verdict="agreed",
      wrong="E[W] = D - E[costs] was asserted for every policy and repeated for the trailing futures accounts.",
      fix="General form E[W] = -E[X_end] - E[total cost] (cycle-by-cycle optional stopping, each cycle a bounded stopped "
          "sum); D - E[cost] only when the account always ends at -D. The chain reports E[X_end] and the identity gap "
          "([[FUND_GAP]]). The futures text no longer claims the identity."),
 dict(n=9, title="GFT's expected-cycle formula", verdict="agreed",
      wrong="q1/(1 - q) was printed for two special first cycles.",
      fix="E[paid cycles] = q_a + q_a^2/(1 - q_b), with gross withdrawals X_a(q_a + q_a^2) + X_b q_a^2 q_b/(1 - q_b)."),
 dict(n=10, title="Account-size scaling scaled the refund", verdict="agreed, extended",
      wrong="lambda P E[C](S) - F(lambda S) scales a refund that follows the fee actually paid.",
      fix="E[V(lambda S)] = P[lambda G(S) + q_R R(lambda S)] - F(lambda S). Version 7 also makes every dollar tolerance in "
          "the engine scale with the account, and checks pathwise on the same seeds that a 200K account is exactly twice a "
          "100K account where the rules scale ([[SCALE_TEST]]). Where a rule is a flat dollar amount (GFT's caps, The5ers' $150 "
          "minimum payout) the scaling is not exact, and the size chapters use each size's own simulation. Version 6's FTMO 200K was not exactly 2x because one $0.50 tolerance did not scale."),
 dict(n=11, title="Larger-target-first does not reduce total trades", verdict="agreed",
      wrong="The claim inferred lower total cost from the lower chance of entering phase 2.",
      fix="Removed. The reviewer's count (11.11 trades vs 10.37 reversed) is reproduced in the text."),
 dict(n=12, title="A larger funded target does not reduce lifetime trades", verdict="agreed",
      wrong="Section 9.3 contradicted section 7.3.", fix="Section 9.3's claim is removed; the measured effect of X is reported."),
 dict(n=13, title="Arithmetic vs geometric Brownian motion", verdict="agreed",
      wrong="Duration formulas derived for driftless arithmetic motion were called exact for the geometric synthetic paths.",
      fix="Labelled as approximations (log barriers -log(1 - s), log(1 + u); log drift -sigma^2/2); the price level, not the "
          "log price, is the martingale. Durations in the document are measured by the engine."),
 dict(n=14, title="'One trade' examples ignored caps", verdict="agreed",
      wrong="Examples showed wins beyond daily targets, best-day caps and the GFT day cap.",
      fix="Examples are generated from the engine's sizing function with every cap (concentration policy, profitable-day "
          "daily targets, best-day and day caps)."),
 dict(n=15, title="Minimum and profitable days do not change only time", verdict="agreed",
      wrong="'Time, not value' was asserted; filler trades can take an account back under its target.",
      fix="Joint success condition: the target plus a $20 per $100K buffer is reached and the required days are complete "
          "(filler days counted as weekdays, 5 in 7); profitable-day rules use daily targets. The claim is removed."),
 # ---------------------------------------------------------------- B. firm rules
 dict(n=16, title="FundingPips 2 Step Flex inputs", verdict="agreed",
      wrong="85% split and 10%/6% targets.",
      fix="Official page: 10%/8%; 80% with 1 minimum trading day, or 95% with 3 profitable days (>= 0.5%) in each phase and "
          "cycle; 4% daily; 12% maximum; no fee refund on Flex. Both options are optimised."),
 dict(n=17, title="GFT rule discrepancies", verdict="agreed, extended",
      wrong="8% phase 1, no valid-day rule, 1:15 index leverage; Goat Guard missing.",
      fix="10%/5%; days count only with >= 0.5% profit (3 per phase, 4 per funded cycle); funded indices 1:10, so the stop "
          "is at least 0.92 sd on the Nasdaq (USDJPY at 1:50 is searched too); daily limit flat at the reset. The $3,000 "
          "day cap is flat at every size (version 6 doubled it at 200K - a further error). Goat Guard triggers at a 2% "
          "combined floating loss; one open position never risks more than 1.75% plus cost, so it cannot trigger without "
          "an intraday gap."),
 dict(n=18, title="FundedNext payout interval", verdict="agreed", wrong="Every 21 days.",
      fix="First reward 21 days after funding, then every 14."),
 dict(n=19, title="Maven's rolling payout cap", verdict="agreed, extended",
      wrong="The cap was not enforced; a 50% best-day rule was assumed.",
      fix="$10,000 per rolling 30 days across all Maven accounts; the plan never requests a payout the cap would cut (it "
          "waits until the window has room; excess is voided otherwise). Official FAQ also: largest winning trade <= 20% "
          "of the profit withdrawn (now modelled), no trade at 1:1.25 or lower (the plan's Maven trades are >= 1:1.5), "
          "risk interview after $5,000 (operational step), no opening or closing within 2 minutes of red-folder news."),
 dict(n=20, title="Anti-gambling rules", verdict="agreed",
      wrong="Compliance was inferred from 1.5% risk and a stop.",
      fix="Concentration policy: no trade and no day may make more than 40% of the current target, so every phase and "
          "payout takes at least three winning days. Behavioural rules are listed per firm as applicability conditions "
          "(chapter 'What could make the numbers wrong', section 2), not as refusal probabilities; the document no longer claims every rule is met, only "
          "every rule that the engine models."),
 dict(n=21, title="News procedure", verdict="agreed",
      wrong="Only US releases; only funded accounts flat before news.",
      fix="Firm-by-firm news rules (Maven applies to evaluations too); a bounding sensitivity in which every account is flat "
          "12:00-14:00 UTC every weekday (also 08:00-09:00 UTC on EURUSD): [[NEWS_RESULT]]."),
 dict(n=22, title="Futures rule implementation", verdict="agreed",
      wrong="Only two Apex caps printed; 'at most 50%'; no expiry; fractional contracts; Topstep transitions not stated.",
      fix="All six Apex caps (in the engine since version 5, now printed); strict < 50%; 30-day evaluation expiry; whole "
          "micro contracts (risk rounded down); Topstep's floor moves to the start balance after the first payout and "
          "every later payout needs net profit since the last one."),
 dict(n=23, title="BrightFunded's 60-second rule", verdict="agreed",
      wrong="Misdescribed; a mean duration is not a minimum.",
      fix="A day counts if at least one trade stays open 60 s; filler trades are held at least 2 minutes (also Alpha's "
          "average-duration rule)."),
 dict(n=24, title="The5ers credit treated as cash", verdict="agreed",
      wrong="All of the fee was modelled as cash with the first payout.",
      fix="10% and 20% of the fee are non-cash hub credit at the phase passes, spent on the slot's next The5ers purchase "
          "(ledger rows credit_earned / credit_used; cash fees paid net of credit); 70% is paid with the first payout."),
 dict(n=25, title="Margin check at the current balance", verdict="agreed",
      wrong="The 60% margin limit was checked on the starting balance only.",
      fix="At every entry: margin = (l/s)/leverage <= 60% of the current balance (and FunderPro's funded limit, 20% of the "
          "starting balance per asset class - a rule version 6 broke at its chosen stop of 0.35 sd)."),
 # ---------------------------------------------------------------- C. simulation and statistics
 dict(n=26, title="Portfolio run reused optimisation paths", verdict="agreed",
      wrong="The headline used paths 21-28, which selected the settings.",
      fix="Settings frozen first; every portfolio life runs on its own new paths (seeds from 100,000 up), used by no "
          "earlier stage."),
 dict(n=27, title="First-year average vs long-run rate", verdict="agreed",
      wrong="'Linearity says they must agree.'",
      fix="Separate estimands: first-year cash (months 1-12), the long-run rate from 36-month lives (months 13-36), and the "
          "value of the accounts still open at month 12. Linearity is stated for a common horizon only, and checked directly: "
          "on the same paths, the full portfolio minus the sum of its firms run alone is zero within its interval."),
 dict(n=28, title="Dependence-aware confidence intervals", verdict="agreed",
      wrong="Attempts on four reused histories treated as independent.",
      fix="Final programme values: 16 independent paths x 1,500 attempts, cluster-robust ratio CI with the path as the "
          "cluster and Student's t with 15 degrees of freedom (reported next to the attempt-level CI). The engine-against-chain "
          "checks use 24 independent two-year paths with cluster-robust intervals. Portfolio lives are independent (one path "
          "per life). All are Monte Carlo intervals under the model, not predictions."),
 dict(n=29, title="Tie resolution inside a bar", verdict="agreed in part",
      wrong="Exactness was implied for the bridge construction.",
      fix="Each sub-step's extremes are drawn from the Brownian bridge given that sub-step's end points, and sub-steps are "
          "replayed in time order, so the order of the two barriers is exact up to ties inside one sub-step, which fall "
          "back to the fair chance. Convergence test at 12 and 60 sub-steps: [[TIE_RESULT]]."),
 dict(n=30, title="Independence of phases and markets", verdict="agreed",
      wrong="Zero edge was said to imply independent phases and independent markets.",
      fix="Wording fixed (P(pass both) = P1 P(2 | 1)); a sensitivity with all four markets on one joint path at "
          "correlation 0.3: [[CORR_RESULT]]."),
 dict(n=31, title="Refusal fraction", verdict="agreed",
      wrong="The printed survival fraction omitted the refused payment.",
      fix="a r (1 - rho)(1 - e^{-rho r H})/(rho r); the simulation already drops the refused payout and every later one."),
 dict(n=32, title="Median cash does not keep every slot filled", verdict="agreed",
      wrong="The median shortfall was read as sufficient funding.",
      fix="Finite-budget runs: purchases wait until the cash is there; results for several budgets: [[BUDGET_RESULT]]."),
 dict(n=33, title="'The engine is always conservative'", verdict="agreed",
      wrong="Contradicted by the table; agreement was called proof.", fix="Wording: agreement is supporting evidence."),
 dict(n=34, title="Narrower claims", verdict="agreed",
      wrong="'Every programme', 'optimal', the month-12 dip, a non-paired comparison, ratio-based cost stress, "
            "FunderPro's non-monotone cost result, reproducibility.",
      fix="Title and claims limited to the programmes and grids searched; month-12 checked with 36-month lives "
          "([[M12_RESULT]]); paired differences on common seeds; cost stress run as full portfolios; component "
          "decomposition (value and time) for every cost row; the code, seeds and rule snapshots are in the repository."),
 dict(n=35, title="Smaller corrections", verdict="agreed",
      wrong="EUR conversions, percentage points, FunderPro/FundedNext daily-room prose, GFT/The5ers qualifying days, "
            "FundedNext heatmap label, '1:30', clipped K(x) equation, 'full allowance' labels, 'after every fee', sources.",
      fix="FTMO EUR 540 = $607.82 and EUR 1,080 = $1,215.65, BrightFunded EUR 497 = $559.42 and EUR 997 = $1,122.22 (at "
          "1.1256); percentage points written as such; prose regenerated from the sizing function; headline 'after the "
          "fees modelled'; exact source URLs (Appendix E)."),
]

# further errors found while making the fixes (not in the review)
NEW = [
 dict(n="N1", title="FunderPro's chosen stop broke its funded margin rule",
      what="FunderPro funded accounts may use at most 20% of the starting balance as margin per asset class. Version 6's "
           "FunderPro setting (stop 0.35 sd, 1:30 on the Nasdaq) needs about 52% - version 6's largest tier-D value "
           "($7,734 a month) rested on it. Version 7: stop >= 0.92 sd on the Nasdaq, or USDJPY."),
 dict(n="N2", title="GFT's day cap doubled at 200K",
      what="The $3,000 daily profit cap is flat at every account size; version 5/6 scaled it to $6,000 at 200K."),
 dict(n="N3", title="A funded branch overwrote the target and best-day caps",
      what="In the funded profitable-days branch the engine reset the win to k l, discarding the cycle-target and "
           "best-day caps computed just above (FundingPips 95%, Hola Prime, GFT). Fixed: the branch can only lower the win."),
 dict(n="N4", title="Filler days counted weekend days",
      what="Missing minimum days were padded one calendar day each; weekends cannot be trading days (now 7/5 per day)."),
 dict(n="N5", title="A win that closes the gap could fail the target test",
      what="A win sized to reach the target exactly lands a rounding error (about 1e-12) short; the exact comparison then "
           "placed an extra trade risking $1,500 to make $1. One cent of tolerance now; this affected every programme in "
           "version 6 too (there overnight financing also left wins short of the target)."),
 dict(n="N6", title="Maven's consistency rule and gambling definition",
      what="The FAQ's largest-trade rule (<= 20% of the payout's profit) and its 1:1.25 gambling definition were missing; "
           "the 50% best-day rule used instead does not appear in the rules."),
 dict(n="N7", title="Contract rounding on normalised paths",
      what="Synthetic paths start at 100, so contract rounding must use the reference Nasdaq level (31,070), not the path "
           "price; one MNQ contract then loses $62,140 x s at the stop."),
 dict(n="N8", title="Apex best-day test", what="'<=' replaced by the rule's strict '<' (a day of exactly 50% fails)."),
 dict(n="N9", title="Best-day rules were not checked at the payout request",
      what="FXIFY (no day above 25% of a payout's profit, measured against the account's best day ever) and Hola Prime (40% "
           "per payout) were enforced only as a daily cap toward the full payout target. When the payout date came with less "
           "than the full target, the engine paid anyway, which the rule could forbid. The request now waits until the rule "
           "holds. (Found after the version 7 grid and refinement had run; the reported values of the chosen settings include "
           "the fix, the ranking of nearby settings does not.)"),
 dict(n="N10", title="A payout blocked by a consistency rule could wait for ever",
      what="If a win filled beyond its target (a gap), the largest win could exceed Maven's 20% of a payout stopped exactly at "
           "the target; the request then failed at every date and the account waited instead of trading on. Found by the "
           "version 7 verification (Chapter 11). The engine now raises that cycle's target to the profit the rule needs and "
           "keeps trading. Under the plan's daily flat this almost never happens: re-running three affected final settings "
           "on the same seeds moved their values by less than $2 a month. Every figure from the final stage on was "
           "recomputed with the corrected engine."),
 dict(n="N11", title="Cluster intervals need Student's t, and verification needs them too",
      what="Version 7's first pass computed cluster-robust intervals with 1.96 even with 4 clusters (the right multiplier "
           "is 3.18) and compared engine and chain with attempt-level intervals, although thousands of attempts on one "
           "path reuse the same price history dozens of times. The comparison then showed funded cash 'significantly' "
           "different from the chain in both directions on different path sets; single brackets at the same settings "
           "were fair. Intervals now use Student's t for G - 1 degrees of freedom, and the verification uses 24 independent "
           "paths. The same effect explains why the momentum direction rule's monthly value looked worse than a coin "
           "flip: attempts overlapping on one path take the same directions, so its interval is far wider; per trade it "
           "has no edge."),
]
